/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGE_Equipo4;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
/**
 *
 * @author ac653
 */
public class AccesoUsuarios extends javax.swing.JFrame {
        
    private byte intentos = 0;

    /**
     * Creates new form AccesoUsuarios
     */
    
    private Map<String, String> usuariosValidos;
    public AccesoUsuarios() {
        initComponents();
        inicializarUsuarios();
    }
    
    private void inicializarUsuarios(){
        usuariosValidos = new HashMap<>();
        usuariosValidos.put("empleado1@employee.zapateria.com", "empleado1");
        
    }
    private boolean validarContrasenia(){
        // Obten el nombre de usuario desde el campo de texto correspondiente
    String usuario = txtUserName.getText();
    // Obten la contraseña desde el campo de contraseña
    char[] passTemp = txtPassword.getPassword();
    String passAux = new String(passTemp);

    // Define aquí el nombre de usuario correcto junto con la contraseña
    //String usuarioCorrecto = "Administrador"; // Cambia esto por el nombre de usuario esperado
    //String passwordCorrecto = "HalconMilenario"; // Este ya lo tienes definido

    // Comprueba si ambos, el usuario y la contraseña, son correctos
    //boolean flag = usuario.equals(usuarioCorrecto) && passwordCorrecto.equals(passAux);
    return usuariosValidos.containsKey(usuario) && usuariosValidos.get(usuario).equals(passAux);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIngresarDatosUser = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresarDatosUser.setBackground(new java.awt.Color(153, 0, 153));
        lblIngresarDatosUser.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblIngresarDatosUser.setText("Datos del empleado");
        lblIngresarDatosUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblIngresarDatosUser.setOpaque(true);
        jPanel1.add(lblIngresarDatosUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        lblUsuario.setBackground(new java.awt.Color(153, 153, 255));
        lblUsuario.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblUsuario.setText("Usuario");
        lblUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblUsuario.setOpaque(true);
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 72, 100, 30));

        txtUserName.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtUserName.setToolTipText("Ingresa tu usuario");
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 73, 280, 30));

        lblContraseña.setBackground(new java.awt.Color(153, 153, 255));
        lblContraseña.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblContraseña.setText("Contraseña");
        lblContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblContraseña.setOpaque(true);
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 142, 100, 30));

        txtPassword.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        txtPassword.setToolTipText("Ingresa la contraseña");
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 280, 30));

        jCheckBox1.setBackground(new java.awt.Color(153, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));

        btnIngresar.setBackground(new java.awt.Color(102, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 30));

        btnSalir.setBackground(new java.awt.Color(255, 102, 0));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        JCheckBox comboBox = (JCheckBox) evt.getSource();
        if (comboBox.isSelected()) {
            txtPassword.setEchoChar((char) 0); // Mostrar la contraseña
        } else {
            txtPassword.setEchoChar('*'); // Ocultar la contraseña
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(txtUserName.getText().isEmpty() || txtPassword.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, "El nombre de usuario o la contraseña están vacíos", "Error en los datos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            intentos++; // Incrementar el número de intentos de acceso cada vez que se presiona el botón ingresar

            if (validarContrasenia()) { // Método para validar las credenciales (usuario y contraseña)
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Curso().setVisible(true);
                    }
                });
                this.dispose(); // Cierra la ventana de acceso si la validación es correcta
            } else {
                txtPassword.setText(""); // Limpia el campo de contraseña para un nuevo intento
                JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrectos. Intento número " + intentos, "Contraseña o usuario incorrectos", JOptionPane.INFORMATION_MESSAGE);

                if (intentos == 3) { // Verifica si se ha alcanzado el límite de intentos
                    JOptionPane.showMessageDialog(null, "Has excedido el número de intentos", "Verificar datos", JOptionPane.ERROR_MESSAGE);
                    System.exit(0); // Cierra la aplicación después de tres intentos fallidos

                }
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIngresarDatosUser;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
